name: Actions
 
on:
  pull_request: {}
  push: { branches: [SpiralRunner] }
 
env:
  UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
 
jobs:
  build:
    name: Build 
    runs-on: ubuntu-latest
    steps:
     
      # Checkout
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          lfs: true
     
      # Cache
      - uses: actions/cache@v1.1.0
        with:
          path: Library
          key: Library
 
      # Build
      - name: Build project
        uses: webbertakken/unity-builder@v0.10
        with:
          unityVersion: 2021.3.11f1
          targetPlatform: StandaloneWindows64
 
      # Output 
      - uses: actions/upload-artifact@v1
        with:
          name: Build
          path: build
